version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fizzbuzz-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vkrh2fn3zxq4"
s3_prefix = "fizzbuzz-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

