AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Fizzbuzz

  Resources for Fizzbuzz application

Globals:
  Function:
    Timeout: 3

Resources:
  FizzbuzzFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.6
      Events:
        Fizzbuzz:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Method: get
            Path: /fizzbuzz/{number}

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  FizbuzzApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/fizzbuzz/"
  FizzbuzzFunction:
    Description: "Fizzbuzz Lambda Function ARN"
    Value: !GetAtt FizzbuzzFunction.Arn
  FizzbuzzFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt FizzbuzzFunctionRole.Arn
